name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK components
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          target: android-34
          components: |
            platform-tools
            build-tools;34.0.0
            platforms;android-34

      - name: Print environment (debug)
        run: |
          echo "PWD=$(pwd)"
          echo "HOME=$HOME"
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          env | sort

      - name: Verify gradlew exists
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -name gradlew -print

      - name: Permission
        run: chmod +x gradlew

      - name: Build APK
        run: |
          pwd
          ls -la
          ./gradlew clean assembleDebug --stacktrace --warning-mode all

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
